{{- if .Values.mainwebsite.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-dir.fullname" . }}-mainwebsite
  labels:
    {{- include "helm-dir.labels" . | nindent 4 }}
    app.kubernetes.io/component: mainwebsite
spec:
  {{- if not .Values.mainwebsite.autoscaling.enabled }}
  replicas: {{ .Values.mainwebsite.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-dir.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mainwebsite
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-dir.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mainwebsite
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-dir.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: mainwebsite
        image: "{{ .Values.mainwebsite.image.repository }}:{{ .Values.mainwebsite.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.mainwebsite.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.mainwebsite.service.targetPort }}
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        {{- if .Values.mainwebsite.env }}
        env:
          {{- toYaml .Values.mainwebsite.env | nindent 12 }}
        {{- end }}
        {{- with .Values.mainwebsite.probes.liveness }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.mainwebsite.probes.readiness }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.mainwebsite.resources | nindent 12 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.mainwebsite.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mainwebsite.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mainwebsite.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
