version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd mainwebsite && npm install && cd ..
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Building application..."
      - cd mainwebsite && npm run build && cd ..
      - echo "Running tests..."
      - cd mainwebsite && npm test && npm run test:e2e && cd ..
      - echo "Building Docker image..."
      - docker build -t mainwebsite:$CODEBUILD_RESOLVED_SOURCE_VERSION ./mainwebsite
      - docker tag mainwebsite:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aws-info-website:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag mainwebsite:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aws-info-website:latest
  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aws-info-website:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aws-info-website:latest
      - printf '[{"name":"mainwebsite","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aws-info-website:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
  name: BuildArtifact

cache:
  paths:
    - '/root/.npm/**/*'
    - 'mainwebsite/node_modules/**/*'
